import { Inter } from "next/font/google";
import "./globals.css";
import "../css/styles.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'react-toastify/dist/ReactToastify.css';

import Header from "@/components/header";
import Footer from "@/components/footer";
import StoreProvider from "@/lib/storeProvider";
import { getCategories } from "@/api/api";
import { BottomNav } from "@/components/bottomNav";
import { ToastContainer } from "react-toastify";
// import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google",
  // icons: {
  //   icon: '/favicon.ico',
  // },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const categories = await getCategories('filter'); // {categoryList: []} //

  return (
    <html lang="en">
      {/* <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <body className={inter.className}>
        <StoreProvider>
          <Header categories={categories} />
          {children}
          <Footer />
          <BottomNav />
          <ToastContainer className="my-toast" />    {/* we can use most of individual toast classes on the this container and that will be applied to all the toast that apear in this container */}
        </StoreProvider>
      </body>
    </html>
  );
}
