import { Inter } from "next/font/google";
import "./globals.css";
import "../css/styles.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Header from "@/components/header";
import Footer from "@/components/footer";
import StoreProvider from "@/lib/storeProvider";
import { getCategories } from "@/api/api";
import { BottomNav } from "@/components/bottomNav";
// import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const categories = {categoryList: []}// await getCategories('filter'); // ; 

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header categories={categories} />
          {children}
          <Footer />
          <BottomNav />
        </StoreProvider>
      </body>
    </html>
  );
}
