export const remoteAssets = true;

export const locations = [
    { id: 1, name: 'Mumbai' },
    { id: 2, name: 'Delhi' },
    { id: 3, name: 'Kolkata' },
    { id: 4, name: 'Hyderabad' },
    { id: 5, name: 'Ahmedabad' },
    { id: 6, name: 'Chennai' },
    { id: 7, name: 'Bangalore' },
    { id: 8, name: 'Surat' },
    { id: 9, name: 'Pune' },
    { id: 10, name: 'Jaipur' },
    { id: 11, name: 'Lucknow' },
    { id: 12, name: 'Kanpur' },
    { id: 13, name: 'Nagpur' },
    { id: 14, name: 'Indore' },
    { id: 15, name: 'Thane' },
    { id: 16, name: 'Bhopal' },
    { id: 17, name: 'Visakhapa' },
    { id: 18, name: 'Pimpri-Ch' },
    { id: 19, name: 'Patna' },
    { id: 20, name: 'Vadodara' },
    { id: 21, name: 'Ghaziabad' },
    { id: 22, name: 'Ludhiana' },
    { id: 23, name: 'Agra' },
    { id: 24, name: 'Nashik' },
    { id: 25, name: 'Faridabad' },
]

export const NEXT_APP_BASE_URL = 'https://myapps.gsterpsoft.com';


export const dummyUser = {
    "UserId": 14322,
    "UserName": null,
    "UserPassword": "1234",
    "UserFullName": "Rahul kumar Gautam",
    "Email": "mail@gmail.com",
    "MobileNo": "3000000004",
    "Salutation": "",
    "Name": "Rahul kumar Gautam",
    "Address": "Madhya Bangla hayetpur road Batangar 24 pargana Kolkata 700140",
    "Address2": "",
    "Address3": "",
    "Address4": "",
    "City": "Batanagar",
    "Pin": "700120",
    "RegMob1": "3000000004",
    "MobOTP": "",
    "UserType": "DOCTOR",
    "Age": 9,
    "AgeMonth": 0,
    "AgeDay": 7,
    "Gender": 104,
    "GenderDesc": "Male",
    "PartyCode": 998113,
    "PartyId": 945420,
    "MemberId": 479,
    "MPartyCode": "",
    "Qualification": "",
    "SpecialistId": 0,
    "SpecialistDesc": "",
    "RegNo": "",
    "CompanyName": null,
    "Country": 1,
    "State": 3,
    "StateName": "West Bengal",
    "DOB": "2015-09-12T00:00:00",
    "DOBstr": null,
    "AnniversaryDate": "0001-01-01T00:00:00",
    "Aadhaar": "",
    "IsDOBCalculated": null,
    "DeptId": 0,
    "PartyType": 320,
    "PartyTypeDesc": "Doctor",
    "Accode": 0,
    "UserAccessList": null,
    "InsDate": "0001-01-01T00:00:00",
    "InsBy": 0,
    "ModiDate": "0001-01-01T00:00:00",
    "ModiBy": 0,
    "Modistatus": null,
    "DelDate": "0001-01-01T00:00:00",
    "DelBy": 0,
    "Delstatus": null,
    "CompanyId": 0,
    "EncCompanyId": "FFCeIi27FQMTNGpatwiktw==",
    "CompUserPartyCode": 0,
    "CompUserMPartyCode": null,
    "LocationId": 0,
    "FinYear": 0,
    "Remarks": "",
    "RegMode": null,
    "LocationName": null,
    "ExchangeRate": 0,
    "INREquivalent": 0,
    "ForexSign": null,
    "ROUNDOFFHEAD": 0,
    "ROUNDOFF": 0,
    "RoundOffType": null,
    "TermsAndConditions": null,
    "BankDetails": null,
    "CGSTTAXTYPE": 0,
    "SGSTTAXTYPE": 0,
    "IGSTTAXTYPE": 0,
    "CESSTAXTYPE": 0,
    "UTGSTTAXTYPE": 0,
    "IsGST": null,
    "SGSTPACHEAD": 0,
    "CGSTPACHEAD": 0,
    "IGSTPACHEAD": 0,
    "UTGSTPACHEAD": 0,
    "SGSTSUSPACHEAD": 0,
    "CGSTSUSPACHEAD": 0,
    "IGSTSUSPACHEAD": 0,
    "UTGSTSUSPACHEAD": 0,
    "SGSTADVACHEAD": 0,
    "CGSTADVACHEAD": 0,
    "IGSTADVACHEAD": 0,
    "UTGSTADVACHEAD": 0,
    "CESSADVACHEAD": 0,
    "CESSRACHEAD": 0,
    "CESSPACHEAD": 0,
    "CESSRSUSACHEAD": 0,
    "CGST": 0,
    "SGST": 0,
    "IGST": 0,
    "UTGST": 0,
    "CESS": 0,
    "CCESS": 0,
    "ICESS": 0,
    "TotalTax": 0,
    "MRPValue": 0,
    "Savings": 0,
    "SavingsPer": 0,
    "RateCondition": null,
    "ConditionalAmt": 0,
    "CGSTRATE": 0,
    "SGSTRATE": 0,
    "IGSTRATE": 0,
    "OLDCGSTRATE": 0,
    "OLDSGSTRATE": 0,
    "OLDIGSTRATE": 0,
    "ConditionalCGSTRATE": 0,
    "ConditionalSGSTRATE": 0,
    "ConditionalIGSTRATE": 0,
    "UTGSTRATE": 0,
    "CESSRATE": 0,
    "SGSTRACHEAD": 0,
    "CGSTRACHEAD": 0,
    "IGSTRACHEAD": 0,
    "UTGSTRACHEAD": 0,
    "StockInOutQty": 0,
    "VisitNo": null,
    "IsProvisionalInv": null,
    "EC_GSTIN": null,
    "IsReverseCharge": null,
    "CurrencySign": null,
    "ExportUnder": null,
    "VchNoSeries": null,
    "TrackingNo2": null,
    "TrackingNo3": null,
    "TrackingNo4": null,
    "TrackingNo5": null,
    "TrackingNo6": null,
    "NetRateS": 0,
    "ServiceStartTime": null,
    "ServiceEndTime": null,
    "IsCanceled": null,
    "CFACTOR_MRP": 0,
    "PackSizeId": 0,
    "PackSizeDesc": null,
    "UHID": "",
    "ApprovalStatus": null,
    "BillStatus": null,
    "OrderStatus": null,
    "strManufacturingDate": null,
    "ManufacturingDate": "0001-01-01T00:00:00",
    "ExpiryDate": "0001-01-01T00:00:00",
    "ERRORCODE": null,
    "MODCOUNTER": 0,
    "VisitId": 0,
    "VisitRefType": null
}